# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21
minecraft_version_range=[1.21,1.21.1)
# Not sure where mapping goes any more
# mapping_version=1.20.1
# mapping_channel=official
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.0.0-beta
# The Neo version range can use any version of Neo as bounds
neo_version_range=[21.0.0-beta,)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[4,)

mod_id=clash
mod_name=Clash
mod_build_name=clash
mod_version=0.3.2

#https://www.curseforge.com/minecraft/mc-mods/jei/files
jei_version=15.2.0.27

mod_license=ARR
mod_authors=Jsburg, special thanks Piggy
mod_description=AWESOME WEAPON MOD!!!

#read more on this at https://github.com/neoforged/NeoGradle/blob/NG_7.0/README.md#apply-parchment-mappings
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.05.01