modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/jsburger/Clash/issues"
[[mods]]
    modId="clash"
    version="0.3"
    displayName="Clash"
    authors="Jsburg, RENREN, special thanks to Piggy"
    description='''
    AWESOME WEAPON MOD!!!
    '''
[[dependencies.clash]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.clash]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2, 1.19)"
    ordering="NONE"
    side="BOTH"
