modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/jsburger/Clash/issues"
[[mods]]
    modId="${mod_id}"
    namespace="${mod_id}"
    version="${mod_version}"
    displayName="Clash!"
    authors="${mod_authors}"
    description='''${mod_description}'''
    displayURL=""
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
